## To build use 'docker-compose build' or 'docker-compose up --build'
## To run use 'docker-compose up'


version: '3' #version of Docker Compose
services: #running services 
  web: #our webapp
    build: . #the container is built from the local Dockerfile
    ports:
    - '3001:3001' #port mapping
    links:
    - mongo #link web container with mongo container
  mongo:
    image: mongo
    volumes: 
    - mongodata:/data/db
    ports: 
    - "27017:27017"

volumes: 
  mongodata:

